### ISSUE TITLE
List::Gather dependency is problematic

### ISSUE THREAD

**Issue by eserte** [OpusVL/String-Substitute#2]
String::Substitute depends on List::Gather, but unfortunately List::Gather does not build anymore on bleadperl (5.25.x) and it seems that a fix will not happen that fast, see https://rt.cpan.org/Ticket/Display.html?id=116694
Maybe it would be a good idea to not use List::Gather here?

**Comment by Nick-OpusVL** [comment]
Thankyou for the heads up on this one.  I don't have time to fix and test it immediately, but I have added it to my todo list for when I've got a moment.

**Comment by Nick-OpusVL** [comment]
I've sent a release of 0.007, which includes the fix for this, to PAUSE.  Look out for it on CPAN soon.
